#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := ../../code/src/interface.cpp ../../code/src/pn532.cpp ../../code/src/pn532Oled.cpp ../../code/src/pn532Command.cpp ../../code/src/mifareClassic.cpp

# header files in this project
HEADERS := ../../code/headers/interface.h ../../code/headers/pn532.h ../../code/headers/pn532Oled.h ../../code/headers/pn532Command.h ../../code/headers/hardware_uart.h ../../code/headers/declarations.h ../../code/headers/nfc.h ../../code/headers/mifareClassic.h

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ../../
include $(RELATIVE)/Makefile.due
